{
	"version": 1554855318,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/spacebackground.png",
		"images/starsforeground.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground5.png",
		"images/greenprojectile-sheet0.png",
		"images/sprite-sheet0.png",
		"images/collisionbox-sheet0.png",
		"images/gunarmright-sheet0.png",
		"images/platformlarge-sheet0.png",
		"images/terrainunit-sheet0.png",
		"images/terrainunit2-sheet0.png",
		"images/terrainunit3-sheet0.png",
		"images/platformsmall-sheet0.png",
		"images/platformmedium-sheet0.png",
		"images/mediumboulder-sheet0.png",
		"images/spikeballsmall-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/redshoot-sheet0.png",
		"images/oexplosion-sheet0.png",
		"images/oexplosion-sheet1.png",
		"images/oexplosion-sheet2.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/particles.png",
		"images/playbutton-sheet0.png",
		"images/exitbutton-sheet0.png",
		"images/settingsbutton-sheet0.png",
		"images/sprite6-sheet0.png",
		"media/bump fx.ogg",
		"media/explode fx.ogg",
		"media/one shot laser fx.ogg",
		"media/thrust loop fx.ogg",
		"media/washyspaceguitar.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}